version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: List files
          command: ls -R
      - run:
          name: Compile Java code
          command: |
            javac Num.java NumTest.java
      - run:
          name: Run tests
          command: |
            java NumTest > test-results.xml
      - store_artifacts:
          path: test-results.xml
          destination: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
