name: NumCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: List files
      run: ls -R

    - name: Compile and run tests
      run: |
        cd $GITHUB_WORKSPACE
        javac Num.java NumTest.java
        java NumTest > test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
